version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    
  retail-app:
    depends_on:
      postgres:
          condition: service_healthy
    build: 
      context: ./retail_app
    container_name: retail-app
    environment:
      - DB_HOST=postgres
      - DB_NAME=retail
      - DB_USER=appuser
      - DB_PASSWORD=apppassword

volumes:
  pgdata:
